
PC: HELIOS
INTERACTIVE: False

#--------------------------------------------------------
# Base Data

# NITRO
BASE_DATA_DIR: /media/marcelo/HD_8t/Marcelo__Seagate_8tb/Embrapa/Embrapa_Experimentos/Datasets/PlantaDaninha_BoaVista

#--------------------------------------------------------
# Alignment

# Dataset Alignment
ALIGN_DATASET_NAME: Aligned_ecc_affine_interch_45_cen_5

# Alignment Method
ALIGN_METHOD: align_bands_ecc_affine_with_retry

#--------------------------------------------------------
# Segmentation

# Dataset Segmentation
SEG_DATASET_NAME: ecc_affine_interch_45_cen_5__seg_best_band_otsu

# Segmentation Method
SEGMENTATION_METHOD: best_band_otsu_green

#--------------------------------------------------------
# Split

SEED: 20

# EXPERIMENT_NAME = f"{ALIGN_METHOD}--{SEGMENTATION_METHOD}__SEED_{SEED}"
# Embrapa_Experimentos/Datasets/run_preprocessing/{EXPERIMENT_NAME}

#--------------------------------------------------------
# Data Augmentation

DO_AUGMENTANTION: True
# AUG_EXPERIMENT_NAME = EXPERIMENT_NAME + "_AUG"
# AUG_DIR_EXP = .../Datasets/run_preprocessing/{AUG_EXPERIMENT_NAME}

#--------------------------------------------------------
#--------------------------------------------------------
# Model

DATASET_INPUT: align_bands_ecc_affine_with_retry--best_band_otsu_green__SEED_20
EXPERIMENT_NAME: MODEL_SEED_20_EPOCHS_30_AUG

MODEL:
  MODEL_NAME: MobileNetV3Small
  SEED_MODEL: 20

  PRETRAINED: True
  BATCH_SIZE: 8
  EPOCHS: 1
  DROPOUT: 0.2

  NUM_CLASSES_INPUT: 5
  NUM_WORKERS: 4
  PIN_MEMORY: True
  PERSISTENT_WORKERS: True

#--------------------------------------------------------
#--------------------------------------------------------
# SHAP

APPLY_SHAP: False

